apiVersion: v1
kind: Service
metadata:
  name: tensorboard-{{.Values.name}}
  labels:
    name: tensorboard-{{.Values.name}}
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 6006
    targetPort: 6006
  selector:
    app: tensorboard-{{.Values.name}}